from django.urls import path

from formation import calendrierviews, ecommerceviews
from . import views
from django.contrib.auth import views as auth_views
from . import functions,opcoviews,energieviews,mutuelleviews,mutuelleventeviews,evaluateurviews,voyanceviews


urlpatterns = [
    path('', views.loginPage, name="login"),
    path('home/', views.home, name="home"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name='register'),
    path('allUsers/', views.allUsers, name="allUsers"),
    path('bilan/', views.createBilan, name="createBilan"),
    path('listBilan/', views.listBilan, name="listBilan"),
    path('alleventsPage/', views.alleventsPage, name="alleventsPage"),
    path('listBilanAdmin/', views.listBilanAdmin, name="listBilanAdmin"),
    path('updateBilan/<str:pk>/', views.updateBilan, name="updateBilan"),
    path('deleteBilan/<str:pk>/', views.deleteBilan, name="deleteBilan"),
    path('deleteBilanAdmin/<str:pk>/', views.deleteBilanAdmin, name="deleteBilanAdmin"),
    path('approveordeleteuser/<str:pk>/', views.approveordeleteuser, name="approveordeleteuser"),
    path('deleteuser/<str:pk>/', views.deleteuser, name="deleteuser"),
    path('acceptuser/<str:pk>/', views.acceptuser, name="acceptuser"),
    path('delete_event/', views.delete_event, name="delete_event"),
    path('update_event/', views.update_event, name="update_event"),
    path('createSuivi/', views.createSuivi, name="createSuivi"),
    path('SuiviAdmin/', views.SuiviAdmin, name="SuiviAdmin"),
    path('modifiersuivi/<str:pk>/', views.modifiersuivi, name="modifiersuivi"),
    path('deleteSuivi/<str:pk>/', views.deleteSuivi, name="deleteSuivi"),
    path('profileUser/', views.profileUser, name="profileUser"),
    path('Rendezvous/', views.rendezvous, name="Rendezvous"),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="home/password_reset.html"),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="home/password_reset_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="home/password_reset_form.html"),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="home/password_reset_done.html"), name="password_reset_complete"),
    path('model/', views.model, name="model"),
    path('formulaire/', views.stockagedata, name="formulaire"),
    path('deleterendezvous/<str:pk>/', views.deleterendezvous, name="deleterendezvous"),
    path('updateRendezvous/<str:pk>/', views.updateRendezvous, name="updateRendezvous"),
    path('maps/', views.maps, name="maps"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('database_tocsv/', views.database_tocsv, name="database_tocsv"),
    path('download_csv/', views.download_csv, name="download_csv"),
    path('rolebyuser/<str:pk>/', views.rolebyuser, name="rolebyuser"),
    path('allrendezvous/', views.allrendezvous, name="allrendezvous"),
    path('deleterendezvous/<str:pk>/', views.deleterendezvous, name="deleterendezvous"),
    path('addchargevariable/', views.addchargevariable, name="addchargevariable"),
    path('deletechargevariable/<str:pk>/', views.deletechargevariable, name="deletechargevariable"),
    path('updatechargevariable/<str:pk>/', views.updatechargevariable, name="updatechargevariable"),
    path('addchargefixe/', views.addchargefixe, name="addchargefixe"),
    path('deletechargefixe/<str:pk>/', views.deletechargefixe, name="deletechargefixe"),
    path('updatechargefixe/<str:pk>/', views.updatechargefixe, name="updatechargefixe"),
    path('addchargeimprevisionelle/', views.addchargeimprevisionelle, name="addchargeimprevisionelle"),
    path('deletechargeimprevisionelle/<str:pk>/', views.deletechargeimprevisionelle, name="deletechargeimprevisionelle"),
    path('updatechargeimprevisionelle/<str:pk>/', views.updatechargeimprevisionelle, name="updatechargeimprevisionelle"),
    path('listechargefixe/', views.listechargefixe, name="listechargefixe"),
    path('listechargeimprevisionelle/', views.listechargeimprevisionelle, name="listechargeimprevisionelle"),
    path('listechargevariable/', views.listechargevariable, name="listechargevariable"),
    path('stat_rv_par_role/', views.stat_rv_par_role, name="stat_rv_par_role"),
    path('addrendezvousopco/', opcoviews.addrendezvousopco, name="addrendezvousopco"),
    path('approverendezvousopco/<str:pk>/', opcoviews.approverendezvousopco, name="approverendezvousopco"),
    path('ignorerendezvousopco/<str:pk>/', opcoviews.ignorerendezvousopco, name="ignorerendezvousopco"),
    path('deleterendezvousopco/<str:pk>/', opcoviews.deleterendezvousopco, name="deleterendezvousopco"),
    path('updaterendezvousopco/<str:pk>/', opcoviews.updaterendezvousopco, name="updaterendezvousopco"),
    path('listrendezvousopcoadmin/', opcoviews.listrendezvousopcoadmin, name="listrendezvousopcoadmin"),
    path('addrendezenergie/', energieviews.addrendezenergie, name="addrendezenergie"),
    path('ignorerendezvousenergie/<str:pk>/', energieviews.ignorerendezvousenergie, name="ignorerendezvousenergie"),
    path('approverendezvousenergie/<str:pk>/', energieviews.approverendezvousenergie, name="approverendezvousenergie"),
    path('updaterendezvousenergie/<str:pk>/', energieviews.updaterendezvousenergie, name="updaterendezvousenergie"),
    path('deleterendezvousenergie/<str:pk>/', energieviews.deleterendezvousenergie, name="deleterendezvousenergie"),
    path('listrendezvousenergieadmin/', energieviews.listrendezvousenergieadmin, name="listrendezvousenergieadmin"),
    path('addmutuelle/', mutuelleviews.addmutuelle, name="addmutuelle"),
    path('ignorerendezvousmutuelle/<str:pk>/', mutuelleviews.ignorerendezvousmutuelle, name="ignorerendezvousmutuelle"),
    path('approverendezvousmutuelle/<str:pk>/', mutuelleviews.approverendezvousmutuelle, name="approverendezvousmutuelle"),
    path('updaterendezvousmutuelle/<str:pk>/', mutuelleviews.updaterendezvousmutuelle, name="updaterendezvousmutuelle"),
    path('deleterendezvousmutuelle/<str:pk>/', mutuelleviews.deleterendezvousmutuelle, name="deleterendezvousmutuelle"),
    path('listrendezvousmutuelleadmin/', mutuelleviews.listrendezvousmutuelleadmin, name="listrendezvousmutuelleadmin"),
    path('mesrendezvousmutuelle/', mutuelleviews.mesrendezvousmutuelle, name="mesrendezvousmutuelle"),

    
    path('contact/', views.stockagemutuelle, name="stockagemutuelle"),
    path('addmutuellevente/', mutuelleventeviews.addmutuellevente, name="addmutuellevente"),
    path('updaterendezvousmutuellevente/<str:pk>/', mutuelleventeviews.updaterendezvousmutuellevente, name="updaterendezvousmutuellevente"),
    path('deleterendezvousmutuellevente/<str:pk>/', mutuelleventeviews.deleterendezvousmutuellevente, name="deleterendezvousmutuellevente"),
    path('listdesventes/', mutuelleventeviews.listdesventes, name="listdesventes"),
    path('ajouterventemutuelle/<str:pk>/', mutuelleventeviews.ajouterventemutuelle, name="ajouterventemutuelle"),
    path('addventeecommerce/', ecommerceviews.addventeecommerce, name="addventeecommerce"),
    path('updateventeecommerce/<str:pk>/', ecommerceviews.updateventeecommerce, name="updateventeecommerce"),
    path('deleteventeecommerce/<str:pk>/', ecommerceviews.deleteventeecommerce, name="deleteventeecommerce"),
    path('addproduct/', ecommerceviews.addproduct, name="addproduct"),
    path('deleteproduct/<str:pk>/', ecommerceviews.deleteproduct, name="deleteproduct"),
    path('addcategorie/<str:pk>/', ecommerceviews.addcategorie, name="addcategorie"),
    path('listcategorieparproduit/<str:pk>/', ecommerceviews.listcategorieparproduit, name="listcategorieparproduit"),
    path('modfiercategorie/<str:pk>/', ecommerceviews.modfiercategorie, name="modfiercategorie"),
    path('addrendezvousvoyance/', voyanceviews.addrendezvousvoyance, name="addrendezvousvoyance"),
    path('updaterendezvousvoyance/<str:pk>/', voyanceviews.updaterendezvousvoyance, name="updaterendezvousvoyance"),
    path('deletervvoyance/<str:pk>/', voyanceviews.deletervvoyance, name="deletervvoyance"),
    path('ignorerendezvousvoyance/<str:pk>/', voyanceviews.ignorerendezvousvoyance, name="ignorerendezvousvoyance"),
    path('approverendezvousvoyance/<str:pk>/', voyanceviews.approverendezvousvoyance, name="approverendezvousvoyance"),
    path('listrendezvousvoyanceadmin/', voyanceviews.listrendezvousvoyanceadmin, name="listrendezvousvoyanceadmin"),
    path('ajoutersuivicpf/', evaluateurviews.ajoutersuivicpf, name="ajoutersuivicpf"),
    path('deletesuivicpf/<str:pk>/', evaluateurviews.deletesuivicpf, name="deletesuivicpf"),
    path('modifiersuivicpf/<str:pk>/', evaluateurviews.modifiersuivicpf, name="modifiersuivicpf"),
    path('listsuivicpf/', evaluateurviews.listsuivicpf, name="listsuivicpf"),
    path('ajoutersuivimutuelle/', evaluateurviews.ajoutersuivimutuelle, name="ajoutersuivimutuelle"),
    path('modifiersuivimutuelle/<str:pk>/', evaluateurviews.modifiersuivimutuelle, name="modifiersuivimutuelle"),
    path('deletesuivimutuellesante/<str:pk>/', evaluateurviews.deletesuivimutuellesante, name="deletesuivimutuellesante"),
    path('listsuivimutellesante/', evaluateurviews.listsuivimutellesante, name="listsuivimutellesante"),
    path('facturerv/', views.facturerv, name="facturerv"),
    path('facturevente/', views.facturevente, name="facturevente"),
    path('ajoutersuiviopco/', evaluateurviews.ajoutersuiviopco, name="ajoutersuiviopco"),
    path('modifiersuiviopco/<str:pk>/', evaluateurviews.modifiersuiviopco, name="modifiersuiviopco"),
    path('deletesuiviopco/<str:pk>/', evaluateurviews.deletesuiviopco, name="deletesuiviopco"),
    path('listsuiviopco/', evaluateurviews.listsuiviopco, name="listsuiviopco"),
    path('ajoutersuivien/', evaluateurviews.ajoutersuivien, name="ajoutersuivien"),
    path('deletesuivien/<str:pk>/', evaluateurviews.deletesuivien, name="deletesuivien"),
    path('modifiersuivien/<str:pk>/', evaluateurviews.modifiersuivien, name="modifiersuivien"),
    path('listsuivien/', evaluateurviews.listsuivien, name="listsuivien"),
    path('ajoutersuivivoyance/', evaluateurviews.ajoutersuivivoyance, name="ajoutersuivivoyance"),
    path('modifiersuivivoyance/<str:pk>/', evaluateurviews.modifiersuivivoyance, name="modifiersuivivoyance"),
    path('deletesuivivoyance/<str:pk>/', evaluateurviews.deletesuivivoyance, name="deletesuivivoyance"),
    path('listsuivivoyance/', evaluateurviews.listsuivivoyance, name="listsuivivoyance"),
    path('listcalendrieropco/', calendrierviews.listcalendrieropco, name="listcalendrieropco"),
    path('listcalendrierenergetique/', calendrierviews.listcalendrierenergetique, name="listcalendrierenergetique"),
    path('listcalendriermutuelle/', calendrierviews.listcalendriermutuelle, name="listcalendriermutuelle"),
    path('listcalendriermutuellevente/', calendrierviews.listcalendriermutuellevente, name="listcalendriermutuellevente"),
    path('listcalendriervoyance/', calendrierviews.listcalendriervoyance, name="listcalendriervoyance"),
    path('stat_ecommerce/', views.stat_ecommerce, name="stat_ecommerce"),
    path('stat_energie/', views.stat_energie, name="stat_energie"),
    path('stat_opco/', views.stat_opco, name="stat_opco"),

    







]