# Generated by Django 3.2.6 on 2022-01-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200)),
                ('prenom_client', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('secteur_activite', models.CharField(max_length=200)),
                ('nom_formation', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('nbre_heure', models.IntegerField()),
                ('prix_formation', models.FloatField()),
                ('date_debut', models.DateField()),
                ('categorie', models.CharField(choices=[('cat 1', 'cat 1'), ('cat 2', 'cat 2'), ('cat 3', 'cat 3'), ('cat 4', 'cat 4'), ('cat 5', 'cat 5'), ('cat 6', 'cat 6'), ('cat 7', 'cat 7')], max_length=200, null=True)),
                ('nom_agent', models.CharField(max_length=200)),
                ('prenom_agent', models.CharField(max_length=200)),
            ],
        ),
    ]
