# Generated by Django 3.2.6 on 2022-01-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_bilan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='nbre_heure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='nom_agent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='nom_client',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='nom_formation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='prenom_agent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='prenom_client',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='prix',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='prix_formation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='secteur_activite',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
