# Generated by Django 3.2.6 on 2022-01-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_alter_bilan_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
