# Generated by Django 3.2.6 on 2022-01-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
