# Generated by Django 3.2.6 on 2022-01-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_bilan_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilan',
            name='prix',
        ),
    ]
