# Generated by Django 3.2.6 on 2022-01-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0009_remove_bilan_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('nbre_sec', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bilan',
            name='nbre_heure',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='prix_formation',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='user_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
