# Generated by Django 3.2.6 on 2022-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0010_auto_20220106_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='nom_agent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suivi',
            name='prenom_agent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
