# Generated by Django 3.2.6 on 2022-01-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0011_auto_20220106_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
