# Generated by Django 3.2.6 on 2022-01-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_remove_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('phone_number', models.IntegerField()),
                ('date_rendez_vous', models.DateField()),
                ('date_rendez_vous_prochain', models.DateField()),
                ('secteur', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
