# Generated by Django 3.2.6 on 2022-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='nom_client',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
