# Generated by Django 3.2.6 on 2022-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0014_rendezvous_nom_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='prenom_client',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
