# Generated by Django 4.0 on 2022-01-18 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0015_rendezvous_prenom_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(75), django.core.validators.MinValueValidator(15)])),
                ('profession', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Employeur', 'Employeur')], max_length=200)),
                ('secteur', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('formation', models.CharField(max_length=200)),
                ('loisir', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
