# Generated by Django 4.0 on 2022-01-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0016_stockage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockage',
            name='loisir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
