# Generated by Django 3.2.6 on 2022-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0018_rendezvous_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='objet',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
