# Generated by Django 3.2.6 on 2022-01-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0019_rendezvous_objet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='categorie',
            field=models.CharField(choices=[('Langues', 'Langues'), ('Bureautique', 'Bureautique'), ('Développement Web', 'Développement Web'), ('Infographie', 'Infographie'), ('Web marketing', 'Web marketing'), ("Création d'entreprise", "Création d'entreprise"), ('Monatage vidéo', 'Monatage vidéo')], max_length=200, null=True),
        ),
    ]
