# Generated by Django 3.2.6 on 2022-01-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0020_alter_bilan_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='nbre_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
