# Generated by Django 3.2.6 on 2022-01-22 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0021_suivi_nbre_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='nbre_min',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='nbre_sec',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)]),
        ),
    ]
