# Generated by Django 4.0.1 on 2022-01-27 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0022_auto_20220122_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='age',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='nbre_heure',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='prix_formation',
            field=models.FloatField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
