# Generated by Django 3.2.4 on 2022-02-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0022_auto_20220122_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockage',
            name='profession',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Employeur', 'Employeur'), ('Employé', 'Employé')], max_length=200),
        ),
    ]
