# Generated by Django 3.2.4 on 2022-02-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0023_alter_bilan_age_alter_bilan_nbre_heure_and_more'),
        ('formation', '0023_alter_stockage_profession'),
    ]

    operations = [
    ]
