# Generated by Django 3.2.4 on 2022-09-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0024_merge_20220222_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='user_admin',
            field=models.IntegerField(null=True),
        ),
    ]
