# Generated by Django 3.2.4 on 2022-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0026_auto_20220902_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='user_admin',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
