# Generated by Django 3.2.4 on 2022-09-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0027_alter_bilan_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='user_admin',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
