# Generated by Django 3.2.4 on 2022-09-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0028_suivi_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivi',
            name='user_admin',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
