# Generated by Django 3.2.4 on 2022-09-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0032_auto_20220902_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargefixe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('loyer', models.FloatField(default=0, null=True)),
                ('internet', models.FloatField(default=0, null=True)),
                ('telecom', models.FloatField(default=0, null=True)),
                ('steg', models.FloatField(default=0, null=True)),
                ('soned', models.FloatField(default=0, null=True)),
                ('banque', models.FloatField(default=0, null=True)),
                ('retenuealasource', models.FloatField(default=0, null=True)),
                ('cnss', models.FloatField(default=0, null=True)),
                ('comptable', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chargeimprevisionelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('chargeimp', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chargevariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('salaire', models.FloatField(default=0, null=True)),
                ('credit', models.FloatField(default=0, null=True)),
                ('marketingdigitale', models.FloatField(default=0, null=True)),
                ('voip', models.FloatField(default=0, null=True)),
                ('fiches', models.FloatField(default=0, null=True)),
                ('crm', models.FloatField(default=0, null=True)),
                ('hebergement', models.FloatField(default=0, null=True)),
                ('leads', models.FloatField(default=0, null=True)),
                ('voyants', models.FloatField(default=0, null=True)),
                ('autres', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
