# Generated by Django 3.2.4 on 2022-09-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0033_chargefixe_chargeimprevisionelle_chargevariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_benefice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
