# Generated by Django 3.2.4 on 2022-09-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0034_account_user_benefice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvousopco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('nom_entreprise', models.CharField(max_length=200, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('code_postal', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('siret', models.IntegerField()),
                ('codeape', models.CharField(max_length=200, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=200, null=True)),
                ('identifiant', models.CharField(blank=True, max_length=200, null=True)),
                ('mdp', models.CharField(max_length=200, null=True)),
                ('telephone_comptable', models.IntegerField(blank=True, null=True)),
                ('formation_souhaite', models.CharField(max_length=200)),
                ('effectife_salarie', models.IntegerField()),
                ('dont', models.IntegerField()),
                ('date_rendez_vous', models.DateField()),
                ('etat', models.IntegerField(default=1)),
            ],
        ),
    ]
