# Generated by Django 3.2.4 on 2022-09-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0035_rendezvousopco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvousopco',
            name='secteur_activite',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=200, null=True),
        ),
    ]
