# Generated by Django 3.2.4 on 2022-09-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0036_alter_rendezvousopco_secteur_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvousopco',
            name='mdp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
