# Generated by Django 3.2.4 on 2022-09-05 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0037_alter_rendezvousopco_mdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvousenergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('nom_client', models.CharField(max_length=200, null=True)),
                ('prenom_client', models.CharField(max_length=200, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('code_postal', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(15)])),
                ('Description', models.CharField(max_length=200, null=True)),
                ('date_rendez_vous', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='rendezvousopco',
            name='secteur_activite',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='NON', max_length=200),
        ),
    ]
