# Generated by Django 3.2.4 on 2022-09-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0038_auto_20220905_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousenergie',
            name='etat',
            field=models.IntegerField(default=1),
        ),
    ]
