# Generated by Django 3.2.4 on 2022-09-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0040_rendezvousmutuelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockagerendezvousmutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200, null=True)),
                ('prenom_client', models.CharField(max_length=200, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('code_postal', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('typerv', models.CharField(choices=[('PHYSIQUE', 'PHYSIQUE'), ('TELEPHONIQUE', 'TELEPHONIQUE')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='rendezvousmutuelle',
            name='seule',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=200),
        ),
        migrations.AlterField(
            model_name='rendezvousmutuelle',
            name='typerv',
            field=models.CharField(choices=[('PHYSIQUE', 'PHYSIQUE'), ('TELEPHONIQUE', 'TELEPHONIQUE')], max_length=200),
        ),
    ]
