# Generated by Django 3.2.4 on 2022-09-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0041_auto_20220909_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockagerendezvousmutuelle',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockagerendezvousmutuelle',
            name='nom_client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockagerendezvousmutuelle',
            name='prenom_client',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockagerendezvousmutuelle',
            name='ville',
            field=models.CharField(max_length=200),
        ),
    ]
