# Generated by Django 3.2.4 on 2022-09-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0042_auto_20220909_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockagerendezvousmutuelle',
            name='typerv',
            field=models.CharField(max_length=200),
        ),
    ]
