# Generated by Django 3.2.4 on 2022-09-10 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0043_alter_stockagerendezvousmutuelle_typerv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvousmutuellevente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('nom_client', models.CharField(max_length=200, null=True)),
                ('prenom_client', models.CharField(max_length=200, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('ville', models.CharField(max_length=200, null=True)),
                ('code_postal', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('seule', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=200)),
                ('date_rendez_vous', models.DateField()),
                ('note', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('etat', models.IntegerField(default=1)),
                ('typerv', models.CharField(choices=[('PHYSIQUE', 'PHYSIQUE'), ('TELEPHONIQUE', 'TELEPHONIQUE')], max_length=200)),
            ],
        ),
    ]
