# Generated by Django 3.2.4 on 2022-09-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0045_ventervmutellevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventervmutellevente',
            name='prix',
            field=models.FloatField(default=0, null=True),
        ),
    ]
