# Generated by Django 3.2.4 on 2022-09-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0046_ventervmutellevente_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venteecommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('nom_client', models.CharField(max_length=200, null=True)),
                ('prenom_client', models.CharField(max_length=200, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_rendez_vous', models.DateField()),
                ('prix', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
