# Generated by Django 3.2.4 on 2022-09-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0048_mutuellesante_suivicpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivienergitique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('nbfiche', models.IntegerField()),
                ('nbminute', models.IntegerField()),
                ('dmc', models.FloatField()),
                ('nrp', models.IntegerField()),
                ('nbhroscibletechnique', models.IntegerField()),
                ('nbpasinteresse', models.IntegerField()),
                ('nbpasinteressecilble', models.IntegerField()),
                ('nbrefuscategorique', models.IntegerField()),
                ('nbrepondeur', models.IntegerField()),
                ('nbvente', models.IntegerField()),
                ('nbrendezvous', models.IntegerField()),
                ('nbappel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suiviopco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('nbfiche', models.IntegerField()),
                ('nbminute', models.IntegerField()),
                ('dmc', models.FloatField()),
                ('nrp', models.IntegerField()),
                ('nbhroscibleregime', models.IntegerField()),
                ('nbpasinteresse', models.IntegerField()),
                ('nbpasinteressecilble', models.IntegerField()),
                ('nbrefuscategorique', models.IntegerField()),
                ('nbrepondeur', models.IntegerField()),
                ('nbvente', models.IntegerField()),
                ('nbrendezvous', models.IntegerField()),
                ('nbappel', models.IntegerField()),
            ],
        ),
    ]
