# Generated by Django 3.2.4 on 2022-09-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0050_suivivoyance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorieecommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('produitid', models.IntegerField()),
                ('nomcategorie', models.CharField(max_length=200)),
                ('quantite', models.IntegerField()),
                ('prixunite_achat', models.FloatField()),
                ('prixunite_vente', models.FloatField()),
                ('depences', models.FloatField()),
                ('benefices', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produitecommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=200, null=True)),
                ('prenom_agent', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField()),
                ('user_admin', models.IntegerField(default=0, null=True)),
                ('user_role', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200)),
                ('nomproduit', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
