# Generated by Django 3.2.4 on 2022-09-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0052_rendezvousvoyance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutuellesante',
            name='nbrappel',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suivicpf',
            name='nbrappel',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suivienergitique',
            name='nbrappel',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suiviopco',
            name='nbrappel',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suivivoyance',
            name='nbrappel',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendezvousvoyance',
            name='prix',
            field=models.FloatField(default=0, max_length=200, null=True),
        ),
    ]
