# Generated by Django 3.2.4 on 2022-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0053_auto_20220916_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockagerendezvousmutuelle',
            name='commentaire',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
