# Generated by Django 3.2.4 on 2022-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0054_stockagerendezvousmutuelle_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteecommerce',
            name='codepostal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venteecommerce',
            name='nomcategorie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venteecommerce',
            name='nomproduit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venteecommerce',
            name='quantite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venteecommerce',
            name='trancheage',
            field=models.CharField(choices=[('de 15 à 18', 'de 15 à 18'), ('de 18 à 30', 'de 18 à 30'), ('de 30 à 50', 'de 30 à 50'), ('50 ans et ++', '50 ans et ++')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venteecommerce',
            name='ville',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
