# Generated by Django 3.2.4 on 2022-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0055_auto_20221004_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteecommerce',
            name='trancheage',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Professionnel', 'Professionnel')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
