# Generated by Django 3.2.4 on 2022-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0056_alter_venteecommerce_trancheage'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteecommerce',
            name='colonne',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Professionnel', 'Professionnel')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venteecommerce',
            name='trancheage',
            field=models.CharField(choices=[('de 15 à 18', 'de 15 à 18'), ('de 18 à 30', 'de 18 à 30'), ('de 30 à 50', 'de 30 à 50'), ('50 ans et ++', '50 ans et ++')], max_length=200, null=True),
        ),
    ]
