# Generated by Django 3.2.4 on 2022-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0057_auto_20221004_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieecommerce',
            name='Nb_Vente',
            field=models.IntegerField(default=0),
        ),
    ]
