# Generated by Django 3.2.4 on 2022-10-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0058_categorieecommerce_nb_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousenergie',
            name='heure',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
