# Generated by Django 3.2.4 on 2022-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0060_alter_rendezvousenergie_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvousenergie',
            name='heure',
            field=models.CharField(max_length=200),
        ),
    ]
