# Generated by Django 3.2.4 on 2022-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0061_alter_rendezvousenergie_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousenergie',
            name='date_appel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvousenergie',
            name='date_rappel',
            field=models.DateField(null=True),
        ),
    ]
