# Generated by Django 3.2.4 on 2022-10-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0062_auto_20221004_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousopco',
            name='date_appel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvousopco',
            name='date_rappel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvousopco',
            name='heure',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
