# Generated by Django 3.2.4 on 2022-10-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0064_auto_20221014_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutuellesante',
            name='date_appel',
        ),
        migrations.RemoveField(
            model_name='mutuellesante',
            name='date_rappel',
        ),
        migrations.RemoveField(
            model_name='mutuellesante',
            name='heure',
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='date_appel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='date_rappel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='heure',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
