# Generated by Django 3.2.4 on 2022-10-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0065_auto_20221014_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='date_appel',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_rendezvous',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='formationsouhaitee',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='numdesecu',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='periode_exercise',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='trancheage',
            field=models.CharField(choices=[('de 15 à 18', 'de 15 à 18'), ('de 18 à 30', 'de 18 à 30'), ('de 30 à 50', 'de 30 à 50'), ('50 ans et ++', '50 ans et ++')], max_length=200, null=True),
        ),
    ]
