# Generated by Django 3.2.4 on 2022-10-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0066_auto_20221018_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_rendezvous',
        ),
    ]
