# Generated by Django 3.2.4 on 2022-10-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0067_remove_rendezvous_date_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='centre_formation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bilan',
            name='heure',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilan',
            name='numdesecu',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=200, null=True),
        ),
    ]
