# Generated by Django 3.2.4 on 2022-10-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0068_auto_20221018_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='commentaire',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
