# Generated by Django 3.2.4 on 2022-10-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0069_bilan_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvousmutuellevente',
            old_name='ville',
            new_name='ancienne',
        ),
        migrations.RenameField(
            model_name='rendezvousmutuellevente',
            old_name='date_appel',
            new_name='date_effet',
        ),
        migrations.RenameField(
            model_name='rendezvousmutuellevente',
            old_name='date_rappel',
            new_name='date_vente',
        ),
        migrations.RemoveField(
            model_name='rendezvousmutuellevente',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='rendezvousmutuellevente',
            name='date_rendez_vous',
        ),
        migrations.RemoveField(
            model_name='rendezvousmutuellevente',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='rendezvousmutuellevente',
            name='heure',
        ),
        migrations.RemoveField(
            model_name='rendezvousmutuellevente',
            name='note',
        ),
        migrations.RemoveField(
            model_name='rendezvousmutuellevente',
            name='seule',
        ),
        migrations.RemoveField(
            model_name='rendezvousmutuellevente',
            name='typerv',
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='cotisation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='formule',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='localite',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='mutuellevendue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='nomcommercial',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
