# Generated by Django 3.2.4 on 2022-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0070_auto_20221018_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='etat',
            field=models.IntegerField(default=1),
        ),
    ]
