# Generated by Django 3.2.4 on 2022-10-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0071_rendezvousmutuellevente_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventervmutellevente',
            name='date_rendez_vous',
        ),
    ]
