# Generated by Django 3.2.4 on 2022-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0072_remove_ventervmutellevente_date_rendez_vous'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventervmutellevente',
            name='benefice',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ventervmutellevente',
            name='rendezvousid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
