# Generated by Django 3.2.4 on 2022-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0073_auto_20221018_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousopco',
            name='benefice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
