# Generated by Django 3.2.4 on 2022-10-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0075_rendezvousmutuelle_benefice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvousmutuelle',
            name='benefice',
        ),
        migrations.AddField(
            model_name='rendezvousenergie',
            name='benefice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
