# Generated by Django 3.2.4 on 2022-10-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0076_auto_20221019_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousmutuelle',
            name='benefice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
