# Generated by Django 3.2.4 on 2022-10-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0077_rendezvousmutuelle_benefice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousvoyance',
            name='benefices',
            field=models.FloatField(default=0, null=True),
        ),
    ]
