# Generated by Django 3.2.4 on 2022-10-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0078_rendezvousvoyance_benefices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvousvoyance',
            name='benefices',
        ),
    ]
