# Generated by Django 3.2.4 on 2022-11-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0079_remove_rendezvousvoyance_benefices'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rendezvousmutuellevente',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
