# Generated by Django 3.2.4 on 2022-11-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0080_auto_20221124_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
